# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Azure subscription 1(08d88455-3754-4d45-a48c-ea2fb11751d8)'
        appType: 'webApp'
        WebAppName: 'TestAPIDocker'
        deployToSlotOrASE: true
        ResourceGroupName: 'myResourceGroup'
        SlotName: 'production'
        VirtualApplication: 'TestAPIDocker'
        packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
    - task: PublishBuildArtifacts@1

